/* header guard generated by genheader.pl */
#ifndef _clisp_common_h_
#define _clisp_common_h_

#define CLISP_VERSION "1.0"


#include <defines.h>
#include <atom.h>
#include <scope.h>
#include <function.h>
#include <list.h>
#include <internal_functions.h>


#endif /* _clisp_common_h_ */
