/* header guard generated by genheader.pl */
#ifndef _defines_h_
#define _defines_h_

typedef struct _Function Function;
typedef struct _Atom Atom;
typedef struct _List List;
typedef struct _Scope Scope;
typedef struct _Program Program;

typedef struct _HtabNode HtabNode;
typedef struct _Htab Htab;



#endif /* _defines_h_ */
