/* header guard generated by genheader.pl */
#ifndef _defines_h_
#define _defines_h_

typedef struct _Function Function;
typedef struct _Atom Atom;

typedef struct _Htab_SI_Node Htab_SI_Node;
typedef struct _Htab_SI Htab_SI;



#endif /* _defines_h_ */
