/* header guard generated by genheader.pl */
#ifndef _internal_functions_h_
#define _internal_functions_h_

/*typedef Atom* (*FunctionCallback)(List* args, Scope* scope);*/
#include <function.h>

#define DECL(name)                                      \
  Atom* internal_function_##name(                       \
    const List* args,                                   \
    Scope* scope,                                       \
    char** error_message,                               \
    jmp_buf trace_point)


void init_internal_functions(Scope* global_scope);

DECL(plus);
DECL(minus);
DECL(multiply);
DECL(divide);

DECL(setq);
DECL(defun);
DECL(print);

#undef DECL

#endif /* _internal_functions_h_ */
